exclude: ['blog', 'library', 'api', 'src', 'node_modules', 'bower_components']
include: ['.htaccess']
keep_files: ['blog', 'library', 'brigade', 'api']
# Used to generate our social metadata
url-base: "http://entsoe.eu"
baseurl: "/baltic-conf/tyndp_site"
permalink: pretty
future: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"